# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19119b35311ee1ee803224cab0935c16c394564343f16fadd67e6059c22d254fc2d65bb5d0dee8563012460b0bd0f67e6b3d95975fa49604d3b72d62c7304ae9

test:
  secret_key_base: b876caf53d80b2ee743a68d91a545b68c79293bfb66992b06d8b9491d7f4c73c3bae6e8bd399b8fa4042efc0bbde6c815e97a7ac29e0206fd85e0a38e74c766a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
